vich_uploader:
    db_driver: orm

    mappings:
        introduction_image:
            uri_prefix: assets/uploads/page
            upload_destination: '%kernel.project_dir%/public/assets/uploads/page'

        section_image:
            uri_prefix: assets/uploads/section
            upload_destination: '%kernel.project_dir%/public/assets/uploads/section'

        category_image:
            uri_prefix: assets/uploads/category
            upload_destination: '%kernel.project_dir%/public/assets/uploads/category'

        carousel_image:
            uri_prefix: assets/uploads/category/carousel
            upload_destination: '%kernel.project_dir%/public/assets/uploads/category/carousel'
